import { useEffect, useState } from 'react'
import { getIncident, incidentAction } from '../lib/api'

export default function IntelligencePanel({ incident }) {
  const [data, setData] = useState(null), [whatIf, setWhatIf] = useState(null), [answer, setAnswer] = useState(null)
  useEffect(() => { if (incident) getIncident(incident.id).then(setData).catch(() => setData(null)) }, [incident?.id])
  if (!incident || !data) return null
  const intel = data.intelligence
  const feedback = label => incidentAction(incident.id, `feedback/${label}`).then(() => setData({...data, intelligence:{...intel, feedback:label}}))
  return <section className="intelligence"><div className="card-title"><span>INTERACTIVE INCIDENT LAB</span><i/></div><div className="intel-grid"><article><h3>ROOT CAUSE MAP</h3><div className="graph">{intel.root_cause_graph.map(node => <span key={node.id} className={node.state}>{node.label}</span>)}</div><p>{intel.deployment_correlation.summary}</p></article><article><h3>BUSINESS IMPACT</h3><b>${intel.business_impact.estimated_revenue_at_risk}</b><p>{intel.business_impact.failed_transactions} failed transactions · {intel.business_impact.affected_customers} customers</p></article><article><h3>ANOMALY DNA</h3><p>{intel.anomaly_dna.pattern}</p><small>{intel.anomaly_dna.velocity} VELOCITY · {intel.anomaly_dna.confidence}% CONFIDENCE</small></article></div><div className="intel-actions"><button onClick={() => incidentAction(incident.id, 'what-if', {latency_multiplier:2}).then(setWhatIf)}>WHAT IF DB LATENCY ×2?</button><button onClick={() => incidentAction(incident.id, 'investigate', {question:'What changed before this incident?'}).then(setAnswer)}>ASK INVESTIGATOR</button><button onClick={() => incidentAction(incident.id, 'remediation/approve').then(() => setData({...data, intelligence:{...intel, remediation:{...intel.remediation, approved:true}}}))}>APPROVE PROPOSAL</button></div>{whatIf && <p className="intel-result">Forecast: {whatIf.predicted_latency_ms}ms latency · {whatIf.predicted_error_rate_percent}% error rate · {whatIf.predicted_failed_transactions} failed transactions.</p>}{answer && <p className="intel-result">{answer.answer} <small>({answer.provider})</small></p>}<div className="feedback"><span>Engineer feedback:</span>{['TRUE_POSITIVE','FALSE_POSITIVE','EXPECTED_BEHAVIOR'].map(label => <button className={intel.feedback===label?'selected':''} key={label} onClick={() => feedback(label)}>{label.replaceAll('_',' ')}</button>)}</div></section>
}
